mysql:
  image: mysql
  ports:
    - 3306:3306
  env:
    MYSQL_DATABASE: sqlalchemy_history_test
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
  options: >-
    --health-cmd "mysqladmin ping"
    --health-interval 5s
    --health-timeout 2s
    --health-retries 3