postgres:
  image: postgres
  ports:
    - 5432:5432
  env:
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: sqlalchemy_history_test
  options: >-
    --health-cmd pg_isready
    --health-interval 5s
    --health-timeout 2s
    --health-retries 3