name: Documentation
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: pip install -r requirements/docs.txt
      - name: Build Site
        run: mkdocs build
      - name: deploy site
        run: mkdocs gh-deploy --force