name: "run tests"

inputs:
  python-version:
    default: '3.6'
  db-engine:
    default: 'sqlite'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - uses: psf/black@stable
    - name: Install Tox and any other packages
      run: pip install .[test]
    - name: Run tests
      run: pytest
      env:
        DB: ${{ inputs.db-engine }}