name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
        test_files: ["tests/test_main.py", "tests/test_math_code.py"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install .[test]
      - name: manually triggered tests
        run: |
          pytest ${{ matrix.test_files }} --cov=indi_dummy --cov-report=lcov
      - name: Coveralls
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        uses: coverallsapp/github-action@master
        with:
          debug: true
          path-to-lcov: ./coverage.lcov
          flag-name: lcov-${{ matrix.python }}-py${{ matrix.test_files }}
          parallel: true

  generate-coverage-report:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Coveralls
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
