name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        db-engine: ['sqlite', 'mysql', 'postgres']
    steps:
      - uses: Dummy/run_test@v1
        with:
          python-version: ${{ matrix.python-version }}
          db-engine: ${{ matrix.db-engine }}